version: "3"
services:

  cronn:
    container_name: ${CONTAINER_NAME}-cron
    build:
      context: ./docker/cron
    volumes:
      - ./:/app
    env_file: .env
  app:
    container_name: ${CONTAINER_NAME}-app
    build:
      context: ./docker/php
      args:
        PHP_VERSION: ${PHP_VERSION}
    expose:
      - 9005
      - 9000
    volumes:
      - ./:/app
    env_file: .env
  nginx:
    container_name: ${CONTAINER_NAME}-nginx
    build:
      context: ./docker/nginx
    restart: always
    volumes:
      - './docker/nginx/nginx.template:/etc/nginx/conf.d/nginx.template'
      - './:/app'
      - './development/logs/nginx:/var/log/nginx'
      -  '/etc/nginx/certs/:/etc/nginx/certs/'
    ports:
      - ${DOMAIN_PORT}:${DOMAIN_PORT}
     # - 443:443
    env_file: .env
    command: sh -c "envsubst '$$NGINX_CDN_HOST $$NGINX_CDN_PORT $$NGINX_CDN_DIR $$NGINX_API_HOST $$NGINX_API_PORT $$NGINX_API_DIR $$NGINX_BACKEND_HOST $$NGINX_BACKEND_PORT $$NGINX_BACKEND_DIR $$NGINX_FRONTEND_HOST $$NGINX_FRONTEND_PORT $$NGINX_FRONTEND_DIR $$DOMAIN_PORT $$CONTAINER_NAME' < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
        - app
  mysql:
    container_name: ${CONTAINER_NAME}-mysql
    build: ./docker/mysql
    env_file: .env
    volumes:
      - ./development/server/mysql:/var/lib/mysql
      - ./docker/mysql/config.cnf:/etc/mysql/conf.d/config.cnf
    ports:
      - ${MYSQL_PORT}:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    container_name: ${CONTAINER_NAME}-phpmyadmin
    env_file: .env
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 4545:80
  postgres:
    container_name: ${CONTAINER_NAME}-postgres
    build: ./docker/postgres
    restart: always
    env_file: .env
    volumes:
      - './development/server/postgres:/var/lib/postgresql'
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - postgres
  pgadmin:
    container_name: ${CONTAINER_NAME}-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    env_file: .env
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - 3422:80
    networks:
      - postgres
    restart: unless-stopped
  memcache:
    container_name: ${CONTAINER_NAME}-memcache
    env_file: .env
    image: 'memcached:alpine'
    restart: always
  node:
    container_name: ${CONTAINER_NAME}-node
    env_file: .env
    image: node:9-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: /bin/true
  redis:
    container_name: ${CONTAINER_NAME}-redis
    env_file: .env
    image: redis
    ports:
      - ${REDIS_PORT}:6379
  mailcatcher:
    container_name: ${CONTAINER_NAME}-mailcatcher
    image: schickling/mailcatcher:latest
    ports:
      - ${MAILCATCHER_PORT}:1080
  swagger-ui:
    container_name: ${CONTAINER_NAME}-swagger-ui
    image: swaggerapi/swagger-ui
    ports:
      - ${SWAGGER_UI_PORT}:8080
    env_file: .env
networks:
  postgres:
    driver: bridge
volumes:
  postgres:
  pgadmin:
